[edge]
edge ansible_host=18.184.167.205 ansible_user=ubuntu ansible_ssh_private_key_file=edge_gateway_key.pem

[private:children]
backend
frontend

[backend]
backend ansible_host=10.0.2.47 ansible_user=ubuntu ansible_ssh_private_key_file=backend_key.pem

[frontend]
frontend ansible_host=10.0.2.151 ansible_user=ubuntu ansible_ssh_private_key_file=frontend_key.pem

[private:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ProxyJump=ubuntu@18.184.167.205 -i edge_gateway_key.pem'
