- hosts: backend
  become: true
  tasks:
    - name: Install JRE 17
      ansible.builtin.package:
        name: openjdk-17-jre-headless
        state: present

    - name: Create app user
      ansible.builtin.user:
        name: app
        system: true

    - name: Create /app dir
      ansible.builtin.file:
        path: /app
        state: directory
        owner: app
        group: app
        mode: "0755"
